### ISSUE TITLE
show both the date and the days of the week for the 7-day exercise log and "weekly progress"

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#110]

**Comment by hermansaksono** [comment]
I tried to address this today. Apparently, there's no easy way to address this. In short, we have to pick the x-axis label to show the day or the month/day. What do you think @xinylin360 @andreagparker 

![Screenshot_20190320-165824](https://user-images.githubusercontent.com/9420115/54719747-0d000b00-4b34-11e9-86db-d6db734dedb2.png)

Detailed answer: I wanted to put the day of the month (e.g., 3/20. 4/1) on the second line. Like this:

```
Wed
3/20
```

Apparently, to be able to do that, we have to create a small new class and update the charting module to version 3. But if we update to version 3, our current program will break because we used version 2.

**Comment by takyyon** [comment]
The library we use is not allowing us to set 2 lines actually. Several issues have been raised for this but none worked upon. https://github.com/PhilJay/MPAndroidChart/issues/1617

I am still looking at a workaround though.
